name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    typecheck:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '18.x'

            -   name: Install dependencies
                run: npm ci

            -   name: Codegen
                run: npm run codegen

            -   name: TypeScript check
                run: npm run tsc
    prettier:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '18.x'

            -   name: Install dependencies
                run: npm ci

            -   name: Check formatting
                run: npm run prettier:check
    eslint:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '18.x'

            -   name: Install dependencies
                run: npm ci

            -   name: Lint
                run: npm run lint
